name: CI

on:
  push:
    branches:
      - master
    tags: [ 'v*' ]
  pull_request:
    branches:
      - master


jobs:
  deploy:
    name: Deploy
    environment: pypi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    permissions:
      contents: write  # GitHub Releases
      id-token: write  # Trusted publishing & sigstore
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run:
        python -m pip install -U pip wheel setuptools build twine
    - name: Build dists
      run: |
        python -m build
    - name: Make Release
      uses: aio-libs/create-release@v1.6.6
      with:
        name: aiohttp-theme
        version_file: aiohttp_theme/__init__.py
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dist_dir: dist
        fix_issue_regex: "`#(\\d+) <https://github.com/aio-libs/aiohttp-theme/issues/\\1>`"
        fix_issue_repl: "(#\\1)"
    - name: >-
        Publish 🐍📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
